version: 2
jobs:
    build:
        working_directory: ~/serverless-ide
        docker:
            - image: circleci/node:chakracore-10.6
        steps:
            - checkout
            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "yarn.lock" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run: sudo npm install yarn@1.9.4 --global
            - run: yarn install --frozen-lockfile
            - run: yarn run lerna bootstrap
            - run: yarn run lerna run prepare

            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "yarn.lock" }}

            - run: yarn lint:types
            - run: yarn lint:ts
            - run: yarn test