version: 2
jobs:
    build:
        working_directory: ~/serverless-ide
        docker:
            - image: circleci/node:8.16.0-jessie
        steps:
            - checkout
            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v3-dependencies-{{ checksum "yarn.lock" }}
                      # fallback to using the latest cache if no exact match is found
                      - v3-dependencies-

            - run: sudo npm install yarn@1.15.2 --global
            - run: sudo npm install lerna -g
            - run: yarn install --frozen-lockfile
            - run: lerna bootstrap
            - run: lerna run prepare

            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "yarn.lock" }}

            - run: yarn lint:types
            - run: yarn lint:ts
            - run: yarn test