version: 2
jobs:
    build:
        working_directory: ~/serverless-ide
        docker:
            - image: circleci/node:8.16.0-jessie
        steps:
            - checkout
            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v3-dependencies-{{ checksum "package-lock.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - v3-dependencies-

            - run: sudo npm install lerna -g
            - run: lerna bootstrap
            - run: npm install

            - save_cache:
                  paths:
                      - node_modules
                  key: v3-dependencies-{{ checksum "package-lock.json" }}

            - run: npm run lint:types
            - run: npm run lint:ts
            - run: npm test